title: 年年岁岁人依旧 | 董卿 × 周涛
author: 年年岁岁人依旧
language: zh-CN
timezone: Asia/Shanghai
url: https://chenhuang527.github.io
root: /
source_dir: source
public_dir: public
theme: scholar
pretty_urls:
  trailing_index: false
  trailing_html: true
exclude:
  - '**/*.example'
skip_render:
  - assets/**
  - CNAME
